import * as readlineSync from "readline-sync";
let Vuelta1:number;
let Vuelta2:number;
let Vuelta3:number;
let Vuelta4:number;
let total:number;
let promedio:number;
console.log("--------------------------------------------");
Vuelta1 = readlineSync.questionFloat("ingrese el tiempo de vuelta 1: ");
console.log("--------------------------------------------");
Vuelta2 = readlineSync.questionFloat("ingrese el tiempo de vuelta 2: ");
console.log("--------------------------------------------");
Vuelta3 = readlineSync.questionFloat("ingrese el tiempo de vuelta 3: ");
console.log("--------------------------------------------");
Vuelta4 = readlineSync.questionFloat("ingrese el tiempo de vuelta 4: ");
console.log("--------------------------------------------");
total = Vuelta1 + Vuelta2 + Vuelta3 + Vuelta4;
promedio = total / 4;
console.log("El timepo total es:", total);
console.log("El timepo promedio de vuelta es:", promedio);
